// 01-前端集群/mixmlaal-frontend/mixmlaal-src/mixmlaal-pages/Login.tsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { authService } from '../services/api';
import { useAuth } from '../hooks/useAuth';

function Login() {
  const [activeTab, setActiveTab] = useState('account');
  const [codeCountdown, setCodeCountdown] = useState(0);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const { login } = useAuth();

  // Account login form
  const [accountForm, setAccountForm] = useState({
    account: '',
    password: '',
  });

  // Phone login form
  const [phoneForm, setPhoneForm] = useState({
    phone: '',
    code: '',
  });

  // Email login form
  const [emailForm, setEmailForm] = useState({
    email: '',
    code: '',
  });

  const startCountdown = () => {
    let count = 60;
    setCodeCountdown(count);
    const timer = setInterval(() => {
      count--;
      setCodeCountdown(count);
      if (count <= 0) {
        clearInterval(timer);
      }
    }, 1000);
  };

  const sendCode = async (type: string) => {
    try {
      let data;
      if (type === 'phone') {
        if (!phoneForm.phone) {
          setError('请先输入手机号');
          return;
        }
        data = { phone: phoneForm.phone };
      } else {
        if (!emailForm.email) {
          setError('请先输入邮箱');
          return;
        }
        data = { email: emailForm.email };
      }

      const res = await authService.sendCode(data);
      alert(res.data.message || '验证码发送成功');
      startCountdown();
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '发送验证码失败');
    }
  };

  const handleLoginSuccess = (res: any) => {
    const { token, userInfo, loginType } = res.data;
    login(userInfo, token, loginType);
    navigate('/');
  };

  const handleAccountLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await authService.login({
        account: accountForm.account,
        password: accountForm.password,
        loginType: 'account',
      });
      handleLoginSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '登录失败');
    } finally {
      setLoading(false);
    }
  };

  const handlePhoneLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await authService.login({
        phone: phoneForm.phone,
        verifyCode: phoneForm.code,
        loginType: 'phone',
      });
      handleLoginSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '登录失败');
    } finally {
      setLoading(false);
    }
  };

  const handleEmailLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await authService.login({
        email: emailForm.email,
        verifyCode: emailForm.code,
        loginType: 'email',
      });
      handleLoginSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '登录失败');
    } finally {
      setLoading(false);
    }
  };

  const handleThirdPartyLogin = async (platform: string) => {
    setError('');
    setLoading(true);

    try {
      const mockOpenId = `${platform}_${Date.now()}`;
      const mockNickname = `${platform}用户`;

      const response = await authService.thirdPartyLogin({
        platform,
        openId: mockOpenId,
        nickname: mockNickname,
      });

      if (response.data.isNewUser) {
        alert('欢迎新用户！');
      }

      handleLoginSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '第三方登录失败');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-purple-500 to-indigo-600 p-4">
      <div className="bg-white rounded-lg shadow-xl p-8 w-full max-w-md">
        <h2 className="text-2xl font-bold text-center mb-6 text-gray-800">用户登录</h2>

        {error && (
          <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
            {error}
          </div>
        )}

        {/* Tabs */}
        <div className="mb-6">
          <div className="flex border-b border-gray-200">
            <button
              className={`py-2 px-4 font-medium ${
                activeTab === 'account' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500'
              }`}
              onClick={() => setActiveTab('account')}
            >
              账号密码
            </button>
            <button
              className={`py-2 px-4 font-medium ${
                activeTab === 'phone' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500'
              }`}
              onClick={() => setActiveTab('phone')}
            >
              手机登录
            </button>
            <button
              className={`py-2 px-4 font-medium ${
                activeTab === 'email' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500'
              }`}
              onClick={() => setActiveTab('email')}
            >
              邮箱登录
            </button>
          </div>
        </div>

        {/* Account Login Form */}
        {activeTab === 'account' && (
          <form onSubmit={handleAccountLogin}>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">账号</label>
              <input
                type="text"
                value={accountForm.account}
                onChange={(e) => setAccountForm({ ...accountForm, account: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 mb-2">密码</label>
              <input
                type="password"
                value={accountForm.password}
                onChange={(e) => setAccountForm({ ...accountForm, password: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
            >
              {loading ? '登录中...' : '登录'}
            </button>
          </form>
        )}

        {/* Phone Login Form */}
        {activeTab === 'phone' && (
          <form onSubmit={handlePhoneLogin}>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">手机号</label>
              <input
                type="tel"
                value={phoneForm.phone}
                onChange={(e) => setPhoneForm({ ...phoneForm, phone: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
                pattern="^1[3-9]\d{9}$"
              />
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 mb-2">验证码</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={phoneForm.code}
                  onChange={(e) => setPhoneForm({ ...phoneForm, code: e.target.value })}
                  className="flex-1 border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                />
                <button
                  type="button"
                  onClick={() => sendCode('phone')}
                  disabled={codeCountdown > 0}
                  className="px-4 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
                >
                  {codeCountdown > 0 ? `${codeCountdown}s` : '获取验证码'}
                </button>
              </div>
            </div>
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
            >
              {loading ? '登录中...' : '登录'}
            </button>
          </form>
        )}

        {/* Email Login Form */}
        {activeTab === 'email' && (
          <form onSubmit={handleEmailLogin}>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">邮箱</label>
              <input
                type="email"
                value={emailForm.email}
                onChange={(e) => setEmailForm({ ...emailForm, email: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 mb-2">验证码</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={emailForm.code}
                  onChange={(e) => setEmailForm({ ...emailForm, code: e.target.value })}
                  className="flex-1 border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                />
                <button
                  type="button"
                  onClick={() => sendCode('email')}
                  disabled={codeCountdown > 0}
                  className="px-4 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
                >
                  {codeCountdown > 0 ? `${codeCountdown}s` : '获取验证码'}
                </button>
              </div>
            </div>
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
            >
              {loading ? '登录中...' : '登录'}
            </button>
          </form>
        )}

        {/* Third Party Login */}
        <div className="mt-6">
          <div className="flex items-center gap-4 mb-4">
            <div className="flex-1 h-px bg-gray-300"></div>
            <span className="text-gray-500 text-sm">其他登录方式</span>
            <div className="flex-1 h-px bg-gray-300"></div>
          </div>
          <div className="flex justify-center gap-4">
            <button
              onClick={() => handleThirdPartyLogin('wechat')}
              className="w-12 h-12 rounded-full bg-green-500 flex items-center justify-center text-white font-bold hover:bg-green-600 transition-colors"
              disabled={loading}
            >
              W
            </button>
            <button
              onClick={() => handleThirdPartyLogin('qq')}
              className="w-12 h-12 rounded-full bg-blue-500 flex items-center justify-center text-white font-bold hover:bg-blue-600 transition-colors"
              disabled={loading}
            >
              Q
            </button>
            <button
              onClick={() => handleThirdPartyLogin('weibo')}
              className="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center text-white font-bold hover:bg-red-600 transition-colors"
              disabled={loading}
            >
              V
            </button>
            <button
              onClick={() => handleThirdPartyLogin('alipay')}
              className="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center text-white font-bold hover:bg-blue-700 transition-colors"
              disabled={loading}
            >
              A
            </button>
          </div>
        </div>

        <p className="mt-6 text-center text-gray-600">
          还没有账号？{' '}
          <Link to="/register" className="text-blue-600 hover:underline">
            立即注册
          </Link>
        </p>
      </div>
    </div>
  );
}

export default Login;

// 01-前端集群/mixmlaal-web-h5-mobile/mixmlaal-src/mixmlaal-pages/Login.vue
<template>
  <div class="login-page">
    <van-nav-bar title="用户登录" left-arrow @click-left="$router.back()" />

    <div class="login-content">
      <div class="logo">
        <img src="https://api.dicebear.com/7.x/avataaars/svg?seed=mall" alt="logo" />
        <h2>亿级商城</h2>
      </div>

      <van-tabs v-model:active="activeTab" line-width="50">
        <van-tab title="账号密码" name="account">
          <van-form @submit="handleAccountLogin">
            <van-cell-group inset>
              <van-field
                v-model="accountForm.account"
                name="account"
                label="账号"
                placeholder="请输入账号"
                :rules="[{ required: true, message: '请输入账号' }]"
              />
              <van-field
                v-model="accountForm.password"
                type="password"
                name="password"
                label="密码"
                placeholder="请输入密码"
                :rules="[{ required: true, message: '请输入密码' }]"
              />
            </van-cell-group>
            <div class="submit-btn">
              <van-button round block type="primary" native-type="submit" :loading="loading">
                登录
              </van-button>
            </div>
          </van-form>
        </van-tab>

        <van-tab title="手机登录" name="phone">
          <van-form @submit="handlePhoneLogin">
            <van-cell-group inset>
              <van-field
                v-model="phoneForm.phone"
                name="phone"
                label="手机号"
                placeholder="请输入手机号"
                :rules="[
                  { required: true, message: '请输入手机号' },
                  { pattern: /^1[3-9]\d{9}$/, message: '手机号格式不正确' }
                ]"
              />
              <van-field
                v-model="phoneForm.code"
                name="code"
                label="验证码"
                placeholder="请输入验证码"
                :rules="[{ required: true, message: '请输入验证码' }]"
              >
                <template #button>
                  <van-button size="small" type="primary" @click="sendCode('phone')" :disabled="codeCountdown > 0">
                    {{ codeCountdown > 0 ? `${codeCountdown}s` : '获取验证码' }}
                  </van-button>
                </template>
              </van-field>
            </van-cell-group>
            <div class="submit-btn">
              <van-button round block type="primary" native-type="submit" :loading="loading">
                登录
              </van-button>
            </div>
          </van-form>
        </van-tab>

        <van-tab title="邮箱登录" name="email">
          <van-form @submit="handleEmailLogin">
            <van-cell-group inset>
              <van-field
                v-model="emailForm.email"
                name="email"
                label="邮箱"
                placeholder="请输入邮箱"
                :rules="[
                  { required: true, message: '请输入邮箱' },
                  { pattern: /^[\w\.-]+@[\w\.-]+\.\w+$/, message: '邮箱格式不正确' }
                ]"
              />
              <van-field
                v-model="emailForm.code"
                name="code"
                label="验证码"
                placeholder="请输入验证码"
                :rules="[{ required: true, message: '请输入验证码' }]"
              >
                <template #button>
                  <van-button size="small" type="primary" @click="sendCode('email')" :disabled="codeCountdown > 0">
                    {{ codeCountdown > 0 ? `${codeCountdown}s` : '获取验证码' }}
                  </van-button>
                </template>
              </van-field>
            </van-cell-group>
            <div class="submit-btn">
              <van-button round block type="primary" native-type="submit" :loading="loading">
                登录
              </van-button>
            </div>
          </van-form>
        </van-tab>
      </van-tabs>

      <div class="divider">
        <span>其他登录方式</span>
      </div>

      <div class="third-party">
        <div class="third-party-btn" @click="handleThirdPartyLogin('wechat')">
          <div class="icon wechat">W</div>
          <span>微信</span>
        </div>
        <div class="third-party-btn" @click="handleThirdPartyLogin('qq')">
          <div class="icon qq">Q</div>
          <span>QQ</span>
        </div>
        <div class="third-party-btn" @click="handleThirdPartyLogin('weibo')">
          <div class="icon weibo">V</div>
          <span>微博</span>
        </div>
        <div class="third-party-btn" @click="handleThirdPartyLogin('alipay')">
          <div class="icon alipay">A</div>
          <span>支付宝</span>
        </div>
      </div>

      <div class="footer">
        <span>还没有账号？</span>
        <router-link to="/register">立即注册</router-link>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { showToast, showSuccessToast } from 'vant'
import { useUserStore } from '../store/user'
import { authAPI } from '../utils/api'

const router = useRouter()
const userStore = useUserStore()

const activeTab = ref('account')
const loading = ref(false)
const codeCountdown = ref(0)
const codeTimer = ref(null)

const accountForm = reactive({
  account: '',
  password: ''
})

const phoneForm = reactive({
  phone: '',
  code: ''
})

const emailForm = reactive({
  email: '',
  code: ''
})

const startCountdown = () => {
  let count = 60
  codeCountdown.value = count
  codeTimer.value = setInterval(() => {
    count--
    codeCountdown.value = count
    if (count <= 0) {
      clearInterval(codeTimer.value)
    }
  }, 1000)
}

const sendCode = async (type) => {
  try {
    let data
    if (type === 'phone') {
      if (!phoneForm.phone) {
        showToast('请先输入手机号')
        return
      }
      data = { phone: phoneForm.phone }
    } else {
      if (!emailForm.email) {
        showToast('请先输入邮箱')
        return
      }
      data = { email: emailForm.email }
    }
    
    const res = await authAPI.sendCode(data)
    showSuccessToast(res.data.message)
    startCountdown()
  } catch (error) {
    showToast(error.message || '发送验证码失败')
  }
}

const handleLoginSuccess = (res) => {
  showSuccessToast('登录成功')
  setTimeout(() => {
    router.replace('/user')
  }, 1000)
}

const handleAccountLogin = async () => {
  loading.value = true
  try {
    const res = await userStore.login({
      account: accountForm.account,
      password: accountForm.password,
      loginType: 'account'
    })
    handleLoginSuccess(res)
  } catch (error) {
    showToast(error.message || '登录失败')
  } finally {
    loading.value = false
  }
}

const handlePhoneLogin = async () => {
  loading.value = true
  try {
    const res = await userStore.login({
      phone: phoneForm.phone,
      verifyCode: phoneForm.code,
      loginType: 'phone'
    })
    handleLoginSuccess(res)
  } catch (error) {
    showToast(error.message || '登录失败')
  } finally {
    loading.value = false
  }
}

const handleEmailLogin = async () => {
  loading.value = true
  try {
    const res = await userStore.login({
      email: emailForm.email,
      verifyCode: emailForm.code,
      loginType: 'email'
    })
    handleLoginSuccess(res)
  } catch (error) {
    showToast(error.message || '登录失败')
  } finally {
    loading.value = false
  }
}

const handleThirdPartyLogin = async (platform) => {
  loading.value = true
  try {
    const mockOpenId = `${platform}_${Date.now()}`
    const mockNickname = `${platform}用户`
    
    const res = await userStore.thirdPartyLogin({
      platform,
      openId: mockOpenId,
      nickname: mockNickname
    })
    
    if (res.isNewUser) {
      showToast('欢迎新用户！')
    }
    
    handleLoginSuccess(res)
  } catch (error) {
    showToast(error.message || '第三方登录失败')
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-page {
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-content {
  padding: 30px 20px;
}

.logo {
  text-align: center;
  margin-bottom: 30px;
}

.logo img {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  margin-bottom: 10px;
}

.logo h2 {
  color: #fff;
  font-size: 24px;
  margin: 0;
}

.submit-btn {
  margin: 30px 16px;
}

.divider {
  display: flex;
  align-items: center;
  margin: 30px 0;
  color: #909399;
}

.divider::before,
.divider::after {
  content: '';
  flex: 1;
  height: 1px;
  background: rgba(255, 255, 255, 0.3);
}

.divider span {
  padding: 0 15px;
  color: rgba(255, 255, 255, 0.8);
}

.third-party {
  display: flex;
  justify-content: center;
  gap: 30px;
}

.third-party-btn {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  color: #fff;
}

.third-party-btn .icon {
  width: 48px;
  height: 48px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 20px;
  font-weight: bold;
}

.third-party-btn .icon.wechat {
  background: #07c160;
}

.third-party-btn .icon.qq {
  background: #12b7f5;
}

.third-party-btn .icon.weibo {
  background: #e6162d;
}

.third-party-btn .icon.alipay {
  background: #1677ff;
}

.footer {
  text-align: center;
  margin-top: 40px;
  color: rgba(255, 255, 255, 0.8);
}

.footer a {
  color: #fff;
  text-decoration: none;
  margin-left: 5px;
  font-weight: bold;
}
</style>
