// 01-前端集群/mixmlaal-frontend/mixmlaal-src/mixmlaal-pages/Register.tsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { authService } from '../services/api';

function Register() {
  const [activeTab, setActiveTab] = useState('account');
  const [codeCountdown, setCodeCountdown] = useState(0);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [registeredUserId, setRegisteredUserId] = useState('');
  const navigate = useNavigate();

  // Account register form
  const [accountForm, setAccountForm] = useState({
    account: '',
    nickname: '',
    password: '',
    confirmPassword: '',
  });

  // Phone register form
  const [phoneForm, setPhoneForm] = useState({
    phone: '',
    code: '',
    nickname: '',
    password: '',
  });

  // Email register form
  const [emailForm, setEmailForm] = useState({
    email: '',
    code: '',
    nickname: '',
    password: '',
  });

  const startCountdown = () => {
    let count = 60;
    setCodeCountdown(count);
    const timer = setInterval(() => {
      count--;
      setCodeCountdown(count);
      if (count <= 0) {
        clearInterval(timer);
      }
    }, 1000);
  };

  const sendCode = async (type: string) => {
    try {
      let data;
      if (type === 'phone') {
        if (!phoneForm.phone) {
          setError('请先输入手机号');
          return;
        }
        data = { phone: phoneForm.phone };
      } else {
        if (!emailForm.email) {
          setError('请先输入邮箱');
          return;
        }
        data = { email: emailForm.email };
      }

      const res = await authService.sendCode(data);
      alert(res.data.message || '验证码发送成功');
      startCountdown();
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '发送验证码失败');
    }
  };

  const handleRegisterSuccess = (res: any) => {
    setRegisteredUserId(res.data.userId);
    setShowSuccess(true);
  };

  const handleAccountRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (accountForm.password !== accountForm.confirmPassword) {
      setError('两次输入的密码不一致');
      return;
    }

    setLoading(true);

    try {
      const response = await authService.register({
        account: accountForm.account,
        nickname: accountForm.nickname,
        password: accountForm.password,
        registerType: 'account',
      });
      handleRegisterSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '注册失败');
    } finally {
      setLoading(false);
    }
  };

  const handlePhoneRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await authService.register({
        phone: phoneForm.phone,
        verifyCode: phoneForm.code,
        nickname: phoneForm.nickname || undefined,
        password: phoneForm.password || undefined,
        registerType: 'phone',
      });
      handleRegisterSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '注册失败');
    } finally {
      setLoading(false);
    }
  };

  const handleEmailRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await authService.register({
        email: emailForm.email,
        verifyCode: emailForm.code,
        nickname: emailForm.nickname || undefined,
        password: emailForm.password || undefined,
        registerType: 'email',
      });
      handleRegisterSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '注册失败');
    } finally {
      setLoading(false);
    }
  };

  const goToLogin = () => {
    setShowSuccess(false);
    navigate('/login');
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-purple-500 to-indigo-600 p-4">
      <div className="bg-white rounded-lg shadow-xl p-8 w-full max-w-md">
        <h2 className="text-2xl font-bold text-center mb-6 text-gray-800">用户注册</h2>

        {error && (
          <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
            {error}
          </div>
        )}

        {/* Tabs */}
        <div className="mb-6">
          <div className="flex border-b border-gray-200">
            <button
              className={`py-2 px-4 font-medium ${
                activeTab === 'account' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500'
              }`}
              onClick={() => setActiveTab('account')}
            >
              账号注册
            </button>
            <button
              className={`py-2 px-4 font-medium ${
                activeTab === 'phone' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500'
              }`}
              onClick={() => setActiveTab('phone')}
            >
              手机注册
            </button>
            <button
              className={`py-2 px-4 font-medium ${
                activeTab === 'email' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500'
              }`}
              onClick={() => setActiveTab('email')}
            >
              邮箱注册
            </button>
          </div>
        </div>

        {/* Account Register Form */}
        {activeTab === 'account' && (
          <form onSubmit={handleAccountRegister}>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">账号</label>
              <input
                type="text"
                value={accountForm.account}
                onChange={(e) => setAccountForm({ ...accountForm, account: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">昵称</label>
              <input
                type="text"
                value={accountForm.nickname}
                onChange={(e) => setAccountForm({ ...accountForm, nickname: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">密码</label>
              <input
                type="password"
                value={accountForm.password}
                onChange={(e) => setAccountForm({ ...accountForm, password: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
                minLength={6}
              />
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 mb-2">确认密码</label>
              <input
                type="password"
                value={accountForm.confirmPassword}
                onChange={(e) => setAccountForm({ ...accountForm, confirmPassword: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
            >
              {loading ? '注册中...' : '注册'}
            </button>
          </form>
        )}

        {/* Phone Register Form */}
        {activeTab === 'phone' && (
          <form onSubmit={handlePhoneRegister}>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">手机号</label>
              <input
                type="tel"
                value={phoneForm.phone}
                onChange={(e) => setPhoneForm({ ...phoneForm, phone: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
                pattern="^1[3-9]\d{9}$"
              />
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">验证码</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={phoneForm.code}
                  onChange={(e) => setPhoneForm({ ...phoneForm, code: e.target.value })}
                  className="flex-1 border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                />
                <button
                  type="button"
                  onClick={() => sendCode('phone')}
                  disabled={codeCountdown > 0}
                  className="px-4 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
                >
                  {codeCountdown > 0 ? `${codeCountdown}s` : '获取验证码'}
                </button>
              </div>
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">昵称 (可选)</label>
              <input
                type="text"
                value={phoneForm.nickname}
                onChange={(e) => setPhoneForm({ ...phoneForm, nickname: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 mb-2">密码 (可选)</label>
              <input
                type="password"
                value={phoneForm.password}
                onChange={(e) => setPhoneForm({ ...phoneForm, password: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
            >
              {loading ? '注册中...' : '注册'}
            </button>
          </form>
        )}

        {/* Email Register Form */}
        {activeTab === 'email' && (
          <form onSubmit={handleEmailRegister}>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">邮箱</label>
              <input
                type="email"
                value={emailForm.email}
                onChange={(e) => setEmailForm({ ...emailForm, email: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">验证码</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={emailForm.code}
                  onChange={(e) => setEmailForm({ ...emailForm, code: e.target.value })}
                  className="flex-1 border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                />
                <button
                  type="button"
                  onClick={() => sendCode('email')}
                  disabled={codeCountdown > 0}
                  className="px-4 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
                >
                  {codeCountdown > 0 ? `${codeCountdown}s` : '获取验证码'}
                </button>
              </div>
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">昵称 (可选)</label>
              <input
                type="text"
                value={emailForm.nickname}
                onChange={(e) => setEmailForm({ ...emailForm, nickname: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 mb-2">密码 (可选)</label>
              <input
                type="password"
                value={emailForm.password}
                onChange={(e) => setEmailForm({ ...emailForm, password: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
            >
              {loading ? '注册中...' : '注册'}
            </button>
          </form>
        )}

        <p className="mt-6 text-center text-gray-600">
          已有账号？{' '}
          <Link to="/login" className="text-blue-600 hover:underline">
            立即登录
          </Link>
        </p>
      </div>

      {/* Success Dialog */}
      {showSuccess && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-lg p-8 max-w-md w-full">
            <div className="text-center">
              <div className="w-16 h-16 bg-green-500 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-white text-3xl">✓</span>
              </div>
              <h3 className="text-xl font-bold mb-2">注册成功！</h3>
              <p className="text-gray-600 mb-4">恭喜您完成注册</p>
              <div className="bg-gray-100 rounded p-4 mb-4">
                <p className="text-sm text-gray-500">您的用户ID：</p>
                <p className="text-2xl font-bold text-blue-600">{registeredUserId}</p>
              </div>
              <p className="text-sm text-gray-500 mb-6">请牢记您的用户ID</p>
              <button
                onClick={goToLogin}
                className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 transition-colors"
              >
                立即登录
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default Register;

// 01-前端集群/mixmlaal-web-h5-mobile/mixmlaal-src/mixmlaal-pages/Register.vue
<template>
  <div class="register-page">
    <van-nav-bar title="用户注册" left-arrow @click-left="$router.back()" />

    <div class="register-content">
      <van-tabs v-model:active="activeTab" line-width="50">
        <van-tab title="账号注册" name="account">
          <van-form @submit="handleAccountRegister">
            <van-cell-group inset>
              <van-field
                v-model="accountForm.account"
                name="account"
                label="账号"
                placeholder="请输入账号"
                :rules="[{ required: true, message: '请输入账号' }]"
              />
              <van-field
                v-model="accountForm.nickname"
                name="nickname"
                label="昵称"
                placeholder="请输入昵称"
                :rules="[{ required: true, message: '请输入昵称' }]"
              />
              <van-field
                v-model="accountForm.password"
                type="password"
                name="password"
                label="密码"
                placeholder="请输入密码"
                :rules="[{ required: true, message: '请输入密码' }]"
              />
              <van-field
                v-model="accountForm.confirmPassword"
                type="password"
                name="confirmPassword"
                label="确认密码"
                placeholder="请再次输入密码"
                :rules="[
                  { required: true, message: '请再次输入密码' },
                  {
                    validator: (val) => val === accountForm.password,
                    message: '两次密码不一致'
                  }
                ]"
              />
            </van-cell-group>
            <div class="submit-btn">
              <van-button round block type="primary" native-type="submit" :loading="loading">
                注册
              </van-button>
            </div>
          </van-form>
        </van-tab>

        <van-tab title="手机注册" name="phone">
          <van-form @submit="handlePhoneRegister">
            <van-cell-group inset>
              <van-field
                v-model="phoneForm.phone"
                name="phone"
                label="手机号"
                placeholder="请输入手机号"
                :rules="[
                  { required: true, message: '请输入手机号' },
                  { pattern: /^1[3-9]\d{9}$/, message: '手机号格式不正确' }
                ]"
              />
              <van-field
                v-model="phoneForm.code"
                name="code"
                label="验证码"
                placeholder="请输入验证码"
                :rules="[{ required: true, message: '请输入验证码' }]"
              >
                <template #button>
                  <van-button size="small" type="primary" @click="sendCode('phone')" :disabled="codeCountdown > 0">
                    {{ codeCountdown > 0 ? `${codeCountdown}s` : '获取验证码' }}
                  </van-button>
                </template>
              </van-field>
              <van-field
                v-model="phoneForm.nickname"
                name="nickname"
                label="昵称"
                placeholder="请输入昵称（可选）"
              />
              <van-field
                v-model="phoneForm.password"
                type="password"
                name="password"
                label="密码"
                placeholder="请输入密码（可选）"
              />
            </van-cell-group>
            <div class="submit-btn">
              <van-button round block type="primary" native-type="submit" :loading="loading">
                注册
              </van-button>
            </div>
          </van-form>
        </van-tab>

        <van-tab title="邮箱注册" name="email">
          <van-form @submit="handleEmailRegister">
            <van-cell-group inset>
              <van-field
                v-model="emailForm.email"
                name="email"
                label="邮箱"
                placeholder="请输入邮箱"
                :rules="[
                  { required: true, message: '请输入邮箱' },
                  { pattern: /^[\w\.-]+@[\w\.-]+\.\w+$/, message: '邮箱格式不正确' }
                ]"
              />
              <van-field
                v-model="emailForm.code"
                name="code"
                label="验证码"
                placeholder="请输入验证码"
                :rules="[{ required: true, message: '请输入验证码' }]"
              >
                <template #button>
                  <van-button size="small" type="primary" @click="sendCode('email')" :disabled="codeCountdown > 0">
                    {{ codeCountdown > 0 ? `${codeCountdown}s` : '获取验证码' }}
                  </van-button>
                </template>
              </van-field>
              <van-field
                v-model="emailForm.nickname"
                name="nickname"
                label="昵称"
                placeholder="请输入昵称（可选）"
              />
              <van-field
                v-model="emailForm.password"
                type="password"
                name="password"
                label="密码"
                placeholder="请输入密码（可选）"
              />
            </van-cell-group>
            <div class="submit-btn">
              <van-button round block type="primary" native-type="submit" :loading="loading">
                注册
              </van-button>
            </div>
          </van-form>
        </van-tab>
      </van-tabs>

      <div class="footer">
        <span>已有账号？</span>
        <router-link to="/login">立即登录</router-link>
      </div>
    </div>

    <van-dialog
      v-model:show="showSuccess"
      title="注册成功"
      show-cancel-button
      @confirm="goToLogin"
    >
      <div class="success-dialog">
        <van-icon name="passed" size="80" color="#07c160" />
        <p>恭喜您，注册成功！</p>
        <p class="user-id">您的用户ID：{{ registeredUserId }}</p>
        <p class="tip">请牢记您的用户ID</p>
      </div>
    </van-dialog>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { showToast, showSuccessToast } from 'vant'
import { authAPI } from '../utils/api'

const router = useRouter()

const activeTab = ref('account')
const loading = ref(false)
const showSuccess = ref(false)
const registeredUserId = ref('')
const codeCountdown = ref(0)
const codeTimer = ref(null)

const accountForm = reactive({
  account: '',
  nickname: '',
  password: '',
  confirmPassword: ''
})

const phoneForm = reactive({
  phone: '',
  code: '',
  nickname: '',
  password: ''
})

const emailForm = reactive({
  email: '',
  code: '',
  nickname: '',
  password: ''
})

const startCountdown = () => {
  let count = 60
  codeCountdown.value = count
  codeTimer.value = setInterval(() => {
    count--
    codeCountdown.value = count
    if (count <= 0) {
      clearInterval(codeTimer.value)
    }
  }, 1000)
}

const sendCode = async (type) => {
  try {
    let data
    if (type === 'phone') {
      if (!phoneForm.phone) {
        showToast('请先输入手机号')
        return
      }
      data = { phone: phoneForm.phone }
    } else {
      if (!emailForm.email) {
        showToast('请先输入邮箱')
        return
      }
      data = { email: emailForm.email }
    }
    
    const res = await authAPI.sendCode(data)
    showSuccessToast(res.data.message)
    startCountdown()
  } catch (error) {
    showToast(error.message || '发送验证码失败')
  }
}

const handleRegisterSuccess = (res) => {
  registeredUserId.value = res.data.id
  showSuccess.value = true
}

const handleAccountRegister = async () => {
  loading.value = true
  try {
    const res = await authAPI.register({
      account: accountForm.account,
      nickname: accountForm.nickname,
      password: accountForm.password,
      registerType: 'account'
    })
    handleRegisterSuccess(res)
  } catch (error) {
    showToast(error.message || '注册失败')
  } finally {
    loading.value = false
  }
}

const handlePhoneRegister = async () => {
  loading.value = true
  try {
    const res = await authAPI.register({
      phone: phoneForm.phone,
      verifyCode: phoneForm.code,
      nickname: phoneForm.nickname || undefined,
      password: phoneForm.password || undefined,
      registerType: 'phone'
    })
    handleRegisterSuccess(res)
  } catch (error) {
    showToast(error.message || '注册失败')
  } finally {
    loading.value = false
  }
}

const handleEmailRegister = async () => {
  loading.value = true
  try {
    const res = await authAPI.register({
      email: emailForm.email,
      verifyCode: emailForm.code,
      nickname: emailForm.nickname || undefined,
      password: emailForm.password || undefined,
      registerType: 'email'
    })
    handleRegisterSuccess(res)
  } catch (error) {
    showToast(error.message || '注册失败')
  } finally {
    loading.value = false
  }
}

const goToLogin = () => {
  showSuccess.value = false
  router.replace('/login')
}
</script>

<style scoped>
.register-page {
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.register-content {
  padding: 20px;
}

.submit-btn {
  margin: 30px 16px;
}

.footer {
  text-align: center;
  margin-top: 30px;
  color: rgba(255, 255, 255, 0.8);
}

.footer a {
  color: #fff;
  text-decoration: none;
  margin-left: 5px;
  font-weight: bold;
}

.success-dialog {
  text-align: center;
  padding: 20px 0;
}

.success-dialog p {
  font-size: 16px;
  margin: 15px 0;
}

.success-dialog .user-id {
  background: #f5f7fa;
  padding: 15px;
  border-radius: 8px;
  font-size: 20px;
  font-weight: bold;
  color: #1989fa;
  margin: 20px 0;
}

.success-dialog .tip {
  color: #909399;
  font-size: 14px;
}
</style>
