// 01-前端集群/mixmlaal-web-driver-vue/mixmlaal-src/mixmlaal-views/Login.vue
<template>
  <div class="login-container">
    <div class="login-form">
      <div class="logo">
        <h1>司机/配送员端</h1>
        <p>欢迎登录</p>
      </div>

      <van-tabs v-model:active="activeTab" class="login-tabs" animated>
        <van-tab title="账号登录" name="account"></van-tab>
        <van-tab title="手机登录" name="phone"></van-tab>
        <van-tab title="邮箱登录" name="email"></van-tab>
      </van-tabs>

      <van-form @submit="handleLogin" v-if="activeTab === 'account'">
        <van-cell-group inset>
          <van-field
            v-model="accountForm.account"
            name="account"
            label="账号"
            placeholder="请输入账号"
            :rules="[{ required: true, message: '请输入账号' }]"
          />
          <van-field
            v-model="accountForm.password"
            type="password"
            name="password"
            label="密码"
            placeholder="请输入密码"
            :rules="[{ required: true, message: '请输入密码' }]"
          />
        </van-cell-group>
      </van-form>

      <van-form @submit="handlePhoneLogin" v-if="activeTab === 'phone'">
        <van-cell-group inset>
          <van-field
            v-model="phoneForm.phone"
            name="phone"
            label="手机号"
            placeholder="请输入手机号"
            :rules="[
              { required: true, message: '请输入手机号' },
              { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号' }
            ]"
          />
          <van-field
            v-model="phoneForm.code"
            name="code"
            label="验证码"
            placeholder="请输入验证码"
            :rules="[{ required: true, message: '请输入验证码' }]"
          >
            <template #button>
              <van-button size="small" type="primary" plain @click="sendCode" :disabled="codeCountdown > 0">
                {{ codeCountdown > 0 ? codeCountdown + 's' : '获取验证码' }}
              </van-button>
            </template>
          </van-field>
        </van-cell-group>
      </van-form>

      <van-form @submit="handleEmailLogin" v-if="activeTab === 'email'">
        <van-cell-group inset>
          <van-field
            v-model="emailForm.email"
            name="email"
            label="邮箱"
            placeholder="请输入邮箱"
            :rules="[
              { required: true, message: '请输入邮箱' },
              { pattern: /^[\w\.-]+@[\w\.-]+\.\w+$/, message: '请输入正确的邮箱' }
            ]"
          />
          <van-field
            v-model="emailForm.code"
            name="code"
            label="验证码"
            placeholder="请输入验证码"
            :rules="[{ required: true, message: '请输入验证码' }]"
          >
            <template #button>
              <van-button size="small" type="primary" plain @click="sendEmailCode" :disabled="emailCodeCountdown > 0">
                {{ emailCodeCountdown > 0 ? emailCodeCountdown + 's' : '获取验证码' }}
              </van-button>
            </template>
          </van-field>
        </van-cell-group>
      </van-form>

      <div style="margin: 16px;">
        <van-button round block type="primary" native-type="submit" :loading="loading" @click="handleSubmit">
          登录
        </van-button>
      </div>

      <div class="third-party-login">
        <div class="divider">
          <div class="divider-line"></div>
          <span class="divider-text">其他登录方式</span>
          <div class="divider-line"></div>
        </div>
        <div class="third-party-buttons">
          <button class="third-party-btn wechat" @click="thirdPartyLogin('wechat')">微</button>
          <button class="third-party-btn alipay" @click="thirdPartyLogin('alipay')">支</button>
        </div>
      </div>

      <div class="register-link">
        <span>还没有账号？</span>
        <router-link to="/register">立即注册</router-link>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useDriverStore } from '../mixmlaal-store/driver'
import { showToast } from 'vant'

const router = useRouter()
const driverStore = useDriverStore()

const activeTab = ref('account')
const loading = ref(false)
const codeCountdown = ref(0)
const emailCodeCountdown = ref(0)

const accountForm = reactive({
  account: '',
  password: ''
})

const phoneForm = reactive({
  phone: '',
  code: ''
})

const emailForm = reactive({
  email: '',
  code: ''
})

const sendCode = async () => {
  if (!phoneForm.phone || !/^1[3-9]\d{9}$/.test(phoneForm.phone)) {
    showToast({ message: '请输入正确的手机号', position: 'top' })
    return
  }
  try {
    await driverStore.sendCode({ phone: phoneForm.phone })
    showToast({ message: '验证码已发送', position: 'top' })
    codeCountdown.value = 60
    const timer = setInterval(() => {
      codeCountdown.value--
      if (codeCountdown.value <= 0) clearInterval(timer)
    }, 1000)
  } catch (error) {
    showToast({ message: error.message || '发送失败', position: 'top' })
  }
}

const sendEmailCode = async () => {
  if (!emailForm.email || !/^[\w\.-]+@[\w\.-]+\.\w+$/.test(emailForm.email)) {
    showToast({ message: '请输入正确的邮箱', position: 'top' })
    return
  }
  try {
    await driverStore.sendCode({ email: emailForm.email })
    showToast({ message: '验证码已发送', position: 'top' })
    emailCodeCountdown.value = 60
    const timer = setInterval(() => {
      emailCodeCountdown.value--
      if (emailCodeCountdown.value <= 0) clearInterval(timer)
    }, 1000)
  } catch (error) {
    showToast({ message: error.message || '发送失败', position: 'top' })
  }
}

const handleSubmit = async () => {
  if (activeTab.value === 'account') {
    await handleAccountLogin()
  } else if (activeTab.value === 'phone') {
    await handlePhoneLogin()
  } else {
    await handleEmailLogin()
  }
}

const handleAccountLogin = async () => {
  if (!accountForm.account || !accountForm.password) {
    showToast({ message: '请填写完整信息', position: 'top' })
    return
  }
  try {
    loading.value = true
    await driverStore.login({
      loginType: 'account',
      account: accountForm.account,
      password: accountForm.password
    })
    showToast({ message: '登录成功', position: 'top' })
    router.push('/home')
  } catch (error) {
    showToast({ message: error.message || '登录失败', position: 'top' })
  } finally {
    loading.value = false
  }
}

const handlePhoneLogin = async () => {
  if (!phoneForm.phone || !phoneForm.code) {
    showToast({ message: '请填写完整信息', position: 'top' })
    return
  }
  try {
    loading.value = true
    await driverStore.login({
      loginType: 'phone',
      phone: phoneForm.phone,
      verifyCode: phoneForm.code
    })
    showToast({ message: '登录成功', position: 'top' })
    router.push('/home')
  } catch (error) {
    showToast({ message: error.message || '登录失败', position: 'top' })
  } finally {
    loading.value = false
  }
}

const handleEmailLogin = async () => {
  if (!emailForm.email || !emailForm.code) {
    showToast({ message: '请填写完整信息', position: 'top' })
    return
  }
  try {
    loading.value = true
    await driverStore.login({
      loginType: 'email',
      email: emailForm.email,
      verifyCode: emailForm.code
    })
    showToast({ message: '登录成功', position: 'top' })
    router.push('/home')
  } catch (error) {
    showToast({ message: error.message || '登录失败', position: 'top' })
  } finally {
    loading.value = false
  }
}

const thirdPartyLogin = async (platform) => {
  try {
    loading.value = true
    await driverStore.thirdPartyLogin({
      platform,
      openId: platform + '_' + Date.now(),
      nickname: platform + '司机'
    })
    showToast({ message: '登录成功', position: 'top' })
    router.push('/home')
  } catch (error) {
    showToast({ message: error.message || '登录失败', position: 'top' })
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 20px;
}

.login-form {
  width: 100%;
  max-width: 400px;
  background: #fff;
  padding: 40px 20px;
  border-radius: 10px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
}

.logo {
  text-align: center;
  margin-bottom: 30px;
}

.logo h1 {
  font-size: 24px;
  font-weight: bold;
  color: #f5576c;
  margin-bottom: 10px;
}

.logo p {
  color: #666;
  font-size: 14px;
}

.login-tabs {
  margin-bottom: 20px;
}

.third-party-login {
  margin-top: 30px;
}

.divider {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
}

.divider-line {
  flex: 1;
  height: 1px;
  background: #e0e0e0;
}

.divider-text {
  padding: 0 15px;
  color: #999;
  font-size: 14px;
}

.third-party-buttons {
  display: flex;
  justify-content: center;
  gap: 30px;
}

.third-party-btn {
  width: 50px;
  height: 50px;
  border-radius: 50%;
  border: none;
  color: white;
  font-size: 18px;
  font-weight: bold;
  cursor: pointer;
  transition: transform 0.3s;
}

.third-party-btn:hover {
  transform: scale(1.1);
}

.third-party-btn.wechat {
  background: #07c160;
}

.third-party-btn.alipay {
  background: #1677ff;
}

.register-link {
  text-align: center;
  margin-top: 20px;
  font-size: 14px;
  color: #666;
}

.register-link a {
  color: #f5576c;
  text-decoration: none;
  margin-left: 5px;
}
</style>

// 01-前端集群/mixmlaal-frontend/mixmlaal-src/mixmlaal-pages/Login.tsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { authService } from '../services/api';
import { useAuth } from '../hooks/useAuth';

function Login() {
  const [activeTab, setActiveTab] = useState('account');
  const [codeCountdown, setCodeCountdown] = useState(0);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const { login } = useAuth();

  // Account login form
  const [accountForm, setAccountForm] = useState({
    account: '',
    password: '',
  });

  // Phone login form
  const [phoneForm, setPhoneForm] = useState({
    phone: '',
    code: '',
  });

  // Email login form
  const [emailForm, setEmailForm] = useState({
    email: '',
    code: '',
  });

  const startCountdown = () => {
    let count = 60;
    setCodeCountdown(count);
    const timer = setInterval(() => {
      count--;
      setCodeCountdown(count);
      if (count <= 0) {
        clearInterval(timer);
      }
    }, 1000);
  };

  const sendCode = async (type: string) => {
    try {
      let data;
      if (type === 'phone') {
        if (!phoneForm.phone) {
          setError('请先输入手机号');
          return;
        }
        data = { phone: phoneForm.phone };
      } else {
        if (!emailForm.email) {
          setError('请先输入邮箱');
          return;
        }
        data = { email: emailForm.email };
      }

      const res = await authService.sendCode(data);
      alert(res.data.message || '验证码发送成功');
      startCountdown();
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '发送验证码失败');
    }
  };

  const handleLoginSuccess = (res: any) => {
    const { token, userInfo, loginType } = res.data;
    login(userInfo, token, loginType);
    navigate('/');
  };

  const handleAccountLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await authService.login({
        account: accountForm.account,
        password: accountForm.password,
        loginType: 'account',
      });
      handleLoginSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '登录失败');
    } finally {
      setLoading(false);
    }
  };

  const handlePhoneLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await authService.login({
        phone: phoneForm.phone,
        verifyCode: phoneForm.code,
        loginType: 'phone',
      });
      handleLoginSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '登录失败');
    } finally {
      setLoading(false);
    }
  };

  const handleEmailLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await authService.login({
        email: emailForm.email,
        verifyCode: emailForm.code,
        loginType: 'email',
      });
      handleLoginSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '登录失败');
    } finally {
      setLoading(false);
    }
  };

  const handleThirdPartyLogin = async (platform: string) => {
    setError('');
    setLoading(true);

    try {
      const mockOpenId = `${platform}_${Date.now()}`;
      const mockNickname = `${platform}用户`;

      const response = await authService.thirdPartyLogin({
        platform,
        openId: mockOpenId,
        nickname: mockNickname,
      });

      if (response.data.isNewUser) {
        alert('欢迎新用户！');
      }

      handleLoginSuccess(response);
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.msg || '第三方登录失败');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-purple-500 to-indigo-600 p-4">
      <div className="bg-white rounded-lg shadow-xl p-8 w-full max-w-md">
        <h2 className="text-2xl font-bold text-center mb-6 text-gray-800">用户登录</h2>

        {error && (
          <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
            {error}
          </div>
        )}

        {/* Tabs */}
        <div className="mb-6">
          <div className="flex border-b border-gray-200">
            <button
              className={`py-2 px-4 font-medium ${
                activeTab === 'account' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500'
              }`}
              onClick={() => setActiveTab('account')}
            >
              账号密码
            </button>
            <button
              className={`py-2 px-4 font-medium ${
                activeTab === 'phone' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500'
              }`}
              onClick={() => setActiveTab('phone')}
            >
              手机登录
            </button>
            <button
              className={`py-2 px-4 font-medium ${
                activeTab === 'email' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-gray-500'
              }`}
              onClick={() => setActiveTab('email')}
            >
              邮箱登录
            </button>
          </div>
        </div>

        {/* Account Login Form */}
        {activeTab === 'account' && (
          <form onSubmit={handleAccountLogin}>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">账号</label>
              <input
                type="text"
                value={accountForm.account}
                onChange={(e) => setAccountForm({ ...accountForm, account: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 mb-2">密码</label>
              <input
                type="password"
                value={accountForm.password}
                onChange={(e) => setAccountForm({ ...accountForm, password: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
            >
              {loading ? '登录中...' : '登录'}
            </button>
          </form>
        )}

        {/* Phone Login Form */}
        {activeTab === 'phone' && (
          <form onSubmit={handlePhoneLogin}>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">手机号</label>
              <input
                type="tel"
                value={phoneForm.phone}
                onChange={(e) => setPhoneForm({ ...phoneForm, phone: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
                pattern="^1[3-9]\d{9}$"
              />
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 mb-2">验证码</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={phoneForm.code}
                  onChange={(e) => setPhoneForm({ ...phoneForm, code: e.target.value })}
                  className="flex-1 border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                />
                <button
                  type="button"
                  onClick={() => sendCode('phone')}
                  disabled={codeCountdown > 0}
                  className="px-4 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
                >
                  {codeCountdown > 0 ? `${codeCountdown}s` : '获取验证码'}
                </button>
              </div>
            </div>
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
            >
              {loading ? '登录中...' : '登录'}
            </button>
          </form>
        )}

        {/* Email Login Form */}
        {activeTab === 'email' && (
          <form onSubmit={handleEmailLogin}>
            <div className="mb-4">
              <label className="block text-gray-700 mb-2">邮箱</label>
              <input
                type="email"
                value={emailForm.email}
                onChange={(e) => setEmailForm({ ...emailForm, email: e.target.value })}
                className="w-full border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                required
              />
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 mb-2">验证码</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={emailForm.code}
                  onChange={(e) => setEmailForm({ ...emailForm, code: e.target.value })}
                  className="flex-1 border border-gray-300 rounded px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                />
                <button
                  type="button"
                  onClick={() => sendCode('email')}
                  disabled={codeCountdown > 0}
                  className="px-4 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
                >
                  {codeCountdown > 0 ? `${codeCountdown}s` : '获取验证码'}
                </button>
              </div>
            </div>
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 disabled:bg-gray-400 transition-colors"
            >
              {loading ? '登录中...' : '登录'}
            </button>
          </form>
        )}

        {/* Third Party Login */}
        <div className="mt-6">
          <div className="flex items-center gap-4 mb-4">
            <div className="flex-1 h-px bg-gray-300"></div>
            <span className="text-gray-500 text-sm">其他登录方式</span>
            <div className="flex-1 h-px bg-gray-300"></div>
          </div>
          <div className="flex justify-center gap-4">
            <button
              onClick={() => handleThirdPartyLogin('wechat')}
              className="w-12 h-12 rounded-full bg-green-500 flex items-center justify-center text-white font-bold hover:bg-green-600 transition-colors"
              disabled={loading}
            >
              W
            </button>
            <button
              onClick={() => handleThirdPartyLogin('qq')}
              className="w-12 h-12 rounded-full bg-blue-500 flex items-center justify-center text-white font-bold hover:bg-blue-600 transition-colors"
              disabled={loading}
            >
              Q
            </button>
            <button
              onClick={() => handleThirdPartyLogin('weibo')}
              className="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center text-white font-bold hover:bg-red-600 transition-colors"
              disabled={loading}
            >
              V
            </button>
            <button
              onClick={() => handleThirdPartyLogin('alipay')}
              className="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center text-white font-bold hover:bg-blue-700 transition-colors"
              disabled={loading}
            >
              A
            </button>
          </div>
        </div>

        <p className="mt-6 text-center text-gray-600">
          还没有账号？{' '}
          <Link to="/register" className="text-blue-600 hover:underline">
            立即注册
          </Link>
        </p>
      </div>
    </div>
  );
}

export default Login;
